source 'https://rubygems.org'
 
gem "nokogiri", ">= 1.18.9"
gem "rexml", ">= 3.4.2"

gem 'jekyll'
group :jekyll_plugins do
  gem 'jekyll-gfm-admonitions'
  gem 'jekyll-optional-front-matter'
  gem 'github-pages'
end