name: Upload Mod to NexusMods

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true

jobs:
  upload-to-nexusmods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip mod files
        run: zip -r MuteImpacts_SOS.zip MuteImpacts/*

      - name: Upload mod to NexusMods
        id: upload
        uses: Nexus-Mods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_id: ${{ vars.NEXUSMODS_FILE_ID }}
          filename: MuteImpacts_SOS.zip
          display_name: "MuteImpacts - Silence Obnoxious Sounds (SOS)"
          description: "https://backup158.github.io/MuteImpacts/CHANGELOG"
          # changelog: "https://backup158.github.io/MuteImpacts/CHANGELOG"
          version: ${{ github.event.release.tag_name || github.event.inputs.version }}
          update_mod_version: true
